name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' # 每天 00:00 自动执行
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Pull
        uses: wei/pull@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_ARGS: '--no-edit --author-date-order --ignore-whitespace --no-ff --signoff'
